 apiVersion: apps/v1
 kind: Deployment
 metadata:
   name: flower-service-deployment
 spec:
   selector:
     matchLabels:
       app: flower-service
   replicas: 2
   template:
     metadata:
       labels:
         app: flower-service
     spec:
       containers:
         - name: flower-service
           image: flowerservice:v1
           imagePullPolicy: IfNotPresent
           ports:
             - containerPort: 8080
              
---
apiVersion: v1
kind: Service
metadata:
  name: flower-service-service
spec:
  selector:
    app: flower-service
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8088
    nodePort: 30080
  type: NodePort

