 apiVersion: apps/v1
 kind: Deployment
 metadata:
   name: flowerservice-deployment
 spec:
   selector:
     matchLabels:
       app: flowerservice
   replicas: 2
   template:
     metadata:
       labels:
         app: flowerservice
     spec:
       containers:
         - name: flowerservice
           image: flowerservice:v1
           imagePullPolicy: IfNotPresent
           ports:
             - containerPort: 8080
              
---
apiVersion: v1
kind: Service
metadata:
  name: flowerservice-service
spec:
  selector:
    app: flowerservice
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 30080
  type: NodePort

