 apiVersion: apps/v1
 kind: Deployment
 metadata:
   name: flowerservice-deployment
 spec:
   selector:
     matchLabels:
       app: flowerservice
   replicas: 2
   template:
     metadata:
       labels:
         app: flowerservice
     spec:
       containers:
         - name: flowerservice
           image: flowerservice
           ports:
             - containerPort: 88
---
kind: Service
apiVersion: v1
metadata:
  name: flowerservice-service
  spec:
    selector:
      app: flowerservice
    ports:
    - protocol: TCP
      port: 80
      targetPort: 31000
    type: NodePort

